chaplean-cookie.js:
    path: /cookie-headband.js
    defaults: { _controller: ChapleanCookieBundle:Cookie:cookieHeadband }

chaplean-cookie.min.js:
    path: /cookie-headband.js
    defaults: { _controller: ChapleanCookieBundle:Cookie:cookieHeadband, uglify: true }
