chaplean_cookie_index:
    path: /
    defaults: { _controller: ChapleanCookieBundle:Default:index }

chaplean_cookie_headband:
    path: /cookie-headband.js
    defaults: { _controller: ChapleanCookieBundle:Cookie:cookieHeadband }